# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1033, 243)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1031, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.lyt_main = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.lyt_main.setContentsMargins(0, 0, 0, 0)
        self.lyt_main.setObjectName("lyt_main")

        self.gbx_checkable = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbx_checkable.setCheckable(True)
        self.gbx_checkable.setObjectName("gbx_checkable")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gbx_checkable)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 301, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.rbt_check_true = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_check_true.setChecked(True)
        self.rbt_check_true.setObjectName("rbt_check_true")
        self.verticalLayout.addWidget(self.rbt_check_true, 0, QtCore.Qt.AlignHCenter)
        self.rbt_check_false = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_check_false.setObjectName("rbt_check_false")
        self.verticalLayout.addWidget(self.rbt_check_false, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.lyt_main.addWidget(self.gbx_checkable)
        self.gbx_flat = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbx_flat.setFlat(True)
        self.gbx_flat.setObjectName("gbx_flat")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbx_flat)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 321, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.rbt_flat_true = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbt_flat_true.setChecked(True)
        self.rbt_flat_true.setObjectName("rbt_flat_true")
        self.verticalLayout_2.addWidget(self.rbt_flat_true, 0, QtCore.Qt.AlignHCenter)
        self.rbt_flat_false = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbt_flat_false.setObjectName("rbt_flat_false")
        self.verticalLayout_2.addWidget(self.rbt_flat_false, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.lyt_main.addWidget(self.gbx_flat)
        self.gbx_alignment = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbx_alignment.setObjectName("gbx_alignment")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gbx_alignment)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 301, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.rbt_left = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rbt_left.setChecked(True)
        self.rbt_left.setObjectName("rbt_left")
        self.verticalLayout_3.addWidget(self.rbt_left, 0, QtCore.Qt.AlignHCenter)
        self.rbt_center = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rbt_center.setObjectName("rbt_center")
        self.verticalLayout_3.addWidget(self.rbt_center, 0, QtCore.Qt.AlignHCenter)
        self.rbt_right = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rbt_right.setObjectName("rbt_right")
        self.verticalLayout_3.addWidget(self.rbt_right, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.lyt_main.addWidget(self.gbx_alignment)
        Dialog.setLayout(self.lyt_main)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.rbt_check_true.toggled.connect(self.evt_rbt_check_true_toggled)
        self.rbt_flat_true.toggled.connect(self.evt_rbt_flat_true_toggled)
        self.rbt_left.toggled.connect(self.evt_rbt_alignment_left_toggled)
        self.rbt_center.toggled.connect(self.evt_rbt_alignment_center_toggled)
        self.rbt_right.toggled.connect(self.evt_rbt_alignment_right_toggled)



    def evt_rbt_check_true_toggled(self, checked):
        self.gbx_checkable.setCheckable(checked)

    def evt_rbt_flat_true_toggled(self, checked):
        self.gbx_flat.setFlat(checked)

    def evt_rbt_alignment_left_toggled(self, sld):
        if sld:
            self.gbx_alignment.setAlignment(QtCore.Qt.AlignLeft)
            self.gbx_alignment.setTitle('Left Alignment')

    def evt_rbt_alignment_center_toggled(self, sld):
        if sld:
            self.gbx_alignment.setAlignment(QtCore.Qt.AlignCenter)
            self.gbx_alignment.setTitle('Center Alignment')

    def evt_rbt_alignment_right_toggled(self, sld):
        if sld:
            self.gbx_alignment.setAlignment(QtCore.Qt.AlignRight)
            self.gbx_alignment.setTitle('Right Alignment')


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gbx_checkable.setTitle(_translate("Dialog", "Checkable"))
        self.rbt_check_true.setText(_translate("Dialog", "True"))
        self.rbt_check_false.setText(_translate("Dialog", "False"))
        self.gbx_flat.setTitle(_translate("Dialog", "Flat"))
        self.rbt_flat_true.setText(_translate("Dialog", "True"))
        self.rbt_flat_false.setText(_translate("Dialog", "False"))
        self.gbx_alignment.setTitle(_translate("Dialog", "Left"))
        self.rbt_left.setText(_translate("Dialog", "Align Left"))
        self.rbt_center.setText(_translate("Dialog", "Align Center"))
        self.rbt_right.setText(_translate("Dialog", "Align Right"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
